# -*- coding: utf-8 -*-
"""Testversion.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFf53JIl46JTTUaaQ3TkxiQc2WQrjvsu
"""

print ("Hello World")